services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--stop-writes-on-bgsave-error", "no"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8167:15672"
      - "8168:15692"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

  gateway:
    environment:
      - REDIS_DSN=redis://redis:6379
      - REDIS_STREAM=ws.outbox
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/%2f
      - RABBITMQ_EXCHANGE=ws.outbox
      - RABBITMQ_ROUTING_KEY=ws.outbox
      - RABBITMQ_QUEUE=ws.outbox
      - RABBITMQ_DLQ_EXCHANGE=ws.dlq
      - RABBITMQ_DLQ_QUEUE=ws.dlq

  symfony:
    environment:
      - WS_TRANSPORT_TYPE=redis_stream
      - WS_PRESENCE_TYPE=redis
      - WS_PRESENCE_INTERPRETATION_STRATEGY=none
      - WS_PRESENCE_WRITER_TYPE=none
      - WS_EVENTS_TYPE=redis_stream
      - WS_REDIS_DSN=redis://redis:6379
      - WS_REDIS_STREAM=ws.outbox
      - WS_REDIS_EVENTS_STREAM=ws.events
      - "WS_REDIS_PREFIX=presence:"
      - WS_RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/%2f
      - WS_RABBITMQ_EXCHANGE=ws.outbox
      - WS_RABBITMQ_QUEUE=ws.outbox
      - WS_RABBITMQ_ROUTING_KEY=ws.outbox
      - WS_RABBITMQ_EVENTS_EXCHANGE=ws.events
      - WS_RABBITMQ_EVENTS_QUEUE=ws.events
      - WS_RABBITMQ_EVENTS_ROUTING_KEY=ws.events
